### PR TITLE
Push January event date by a week

### PR DESCRIPTION
**Pull request by billyroh**
Since pushing the event date by a week got the most votes, I'm opening a PR to do so.

We should sure that the two speakers (Liz, Sathya) are available to speak during this date before we merge though?

### CODE REVIEW

**Comment by billyroh** [comment]
@lizhubertz @gsathya Does January 10 (not January 3) still work for you? We're thinking of pushing out by a week since we think a lot of people would be away on January 3 🤔

**Comment by lizhubertz** [comment]
@billyroh works for me!

**Comment by gsathya** [comment]
> @lizhubertz @gsathya Does January 10 (not January 3) still work for you? We're thinking of pushing out by a week since we think a lot of people would be away on January 3 🤔

sure, sounds good to me

**Comment by billyroh** [comment]
Great! I’ll go ahead and merge then. Thanks for being flexible everyone!

**Pull request merged**
