### PR TITLE
Fix issue with alignment

### PR DESCRIPTION
**Pull request by billyroh**
Summary
* Fix issue with blurry text by using `margin-left` instead of `transform`.
* Fix issue with border alignment by using `border-bottom` on child of `li` instead of `li` itself.

Before
screen shot 2015-12-22 at 2 22 46 pm

After
screen shot 2015-12-22 at 2 22 23 pm

### CODE REVIEW

**Comment by billyroh** [comment]
@visnup: The negative `margin-left` is kind of hacky, but it renders better. Let me know what you think~

**Comment by visnup** [comment]
@billyroh what's the difference in spacing for the borders here? I can't see a difference in the screenshots, but maybe my eyes aren't picking it up...

**Comment by billyroh** [comment]
It used to be that the border didn't line up with the right edge of the element above it. So in this example, the border is as wide as the `li` element, which is substantially wider than the `p` and `iframe` elements.
image

In the PR, the border's right edge aligns with the right edge of the element above it. So here, it's as wide as the `p` and `iframe` elements.
image

**Comment by billyroh** [comment]
Ok, I'm gonna merge for now. Let me know if I should roll it back.

**Pull request merged**
