### PR TITLE
Add SparkPost as May 2017 sponsor

### PR DESCRIPTION
**Pull request by kuychaco**
/cc @billyroh is there anything else that needs to be done?

### CODE REVIEW

**Comment by kuychaco** [comment]
Ah, we need an SVG too. Do we typically ask them to provide one?

**Comment by billyroh** [comment]
We'd prefer them to supply the svg. If they don't have one, they could send us an image and I could generate the svg based on that :)

**Comment by kuychaco** [comment]
Cool thanks, sent out an email request 👍

**Comment by kuychaco** [comment]
@billyroh they don't have SVG but gave us a couple .png files (one gray, one color) and a .eps file. Would any of these work?

[SparkPost_Logos.zip](https://github.com/wafflejs/wafflejs.github.io/files/810335/SparkPost_Logos.zip)

**Comment by billyroh** [comment]
Yup, those work! I'll add in the svg in a separate commit. Thanks for getting the zip!

**Pull request merged**
