### PR TITLE
tickets page

### PR DESCRIPTION
**Pull request by visnup**
uses the tito embeddable widget. emojis don't come through correctly though.
tickets

cc @gcochard

### CODE REVIEW

**Comment by visnup** [comment]
re-fixes #29 in a totally different way.

**Comment by gcochard** [comment]
:+1: I like it!

**Comment by visnup** [comment]
ok, let's see how production likes it...

**Comment by gcochard** [comment]
99% of the way there. Going directly to https://wafflejs.com/tickets breaks currently.

**Comment by visnup** [comment]
just fixed.

**Pull request merged**
