### PR TITLE
UPDATE Tre' talk details

### PR DESCRIPTION
**Pull request by Trewaters**
added description, title, and emoji to my talk

```yml
    - 8:00 PM:
        type: Talk
        emoji: 🌄
        title: |
          What is the Dojo?
        description: | 
          The Dojo is what happens when you combine equal parts martial arts and coding paradigms? It creates BJD, the way of the coder. Come see one man struggle to fit heady concepts, like code katas and koans, into a short digestible slide deck. The way of the coder is patterns and practice.
        person:
          name: Tre' Grisby
          github: Trewaters
          pronouns: he/him
```

### CODE REVIEW

**Comment by Trewaters** [comment]
Thanks Max! I see what you were saying. I get so used to interchanging the acronym for the title that I didn't notice.

I made changes to the description and hopefully cleared up some ambiguity.

**Comment by billyroh** [comment]
@Trewaters Do you mind rebasing off of master? Looks like there's a conflict. But the PR looks good otherwise!

**Comment by Trewaters** [comment]
Don't mind at all. I am running around town at the moment but I will grab that tonight.

Tre'

Responding from my cellphone...

________________________________

**Comment by Trewaters** [comment]
This was my first time trying to rebase. I tried to resolve the conflicts and upload them to github but I can't tell if github sees the changes. 

Please let me know if that worked for you. If not I will try again.

**Comment by billyroh** [comment]
That didn't quite work, so I've gone ahead and updated the file myself. You'll see the updated details shortly at https://wafflejs.com/?day=2019-06-05. Looking forward to your talk!

**Comment by Trewaters** [comment]
Sorry about that. I will work on improving my skills in that area. Sorry to make more work for everyone.

**Comment by billyroh** [comment]
No need to apologize!!! Rebasing is probably one of the most painful parts of git, so I totally understand.

**Pull request closed without merging**
